theme: jekyll-theme-architect
title: slai11 blog
email: sylvesterchin.sw@gmail.com
description: "Learning journey of a wannabe engineer"
baseurl: ""
url: "http://slai11.github.io"
twitter_username: slai11
github_username:  slai11